---
- name: php7 - install xdebug
  apt: pkg=php-xdebug state=latest update_cache=yes

- name: Copy xdebug INI into mods-available folder.
  template: >
    src=xdebug.ini.j2
    dest=/etc/php/7.2/mods-available/xdebug.ini
    owner=root group=root mode=644
