---
dependencies: []

galaxy_info:
  author: fubarhouse
  description: Installs Yarn JS package manager.
  license: "license (BSD, MIT)"
  min_ansible_version: 2.1.0.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
    - xenial
  - name: Debian
    versions:
    - all
  - name: EL
    versions:
    - 6
    - 7
  categories:
    - system
    - database
    - development
