---

- name: "Yarn | Install RPM repository"
  become: yes
  become_user: root
  get_url:
    url: http://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    owner: root
    mode: 0644