---
galaxy_info:
  author: Maxime Thoonsen
  description: PHP XDebug for Ubuntu Xenial
  company: "Theodo"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  categories:
    - php
    - web
dependencies: []
